anonymous_banner_text:
  type: string
  default: ""

member_banner_text:
  type: string
  default: ""

insider_banner_text:
  type: string
  default: ""

insider_banner_dismissable:
  type: bool
  default: true

insider_groups:
  default: ""
  type: list
  list_type: group
  resolve_group_membership: true
